
#Create the base Image
FROM python:3.7-slim    

LABEL Author=Saravanan 

#install Dependency
RUN pip install flask==1.1.2

#copy local folder into the container
COPY ./app.py /app/

#Change the working Directory
WORKDIR /app/

#set "Hello World" as the entry point
ENTRYPOINT echo "Hello World"

# set the command as the script name
CMD ["app.py"]
